// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0S0XYk7Lherf5lTkWvdvnjEbkFymyV94',
    appId: '1:677440208167:web:cf7980c7968fdb98c93d02',
    messagingSenderId: '677440208167',
    projectId: 'firestore-root',
    authDomain: 'firestore-root.firebaseapp.com',
    storageBucket: 'firestore-root.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRSovg8qDqWdrPA9RUhSiswjxhAgri5Ow',
    appId: '1:677440208167:android:3b3d205ff41b015bc93d02',
    messagingSenderId: '677440208167',
    projectId: 'firestore-root',
    storageBucket: 'firestore-root.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rIgbl94DFH9mxTubKpYIUbLKtIvWCrQ',
    appId: '1:677440208167:ios:de5ad3d594c67d97c93d02',
    messagingSenderId: '677440208167',
    projectId: 'firestore-root',
    storageBucket: 'firestore-root.appspot.com',
    androidClientId: '677440208167-v3313eu27f8affjm3eg428s07qu7k8lj.apps.googleusercontent.com',
    iosClientId: '677440208167-f1l0b2frmblovtfmteb2v51j7v7o7mo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelSocialApp',
  );
}
