version: '3.1'
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: ./client
    image: react-task/client
    volumes:
      - ./client:/app
      - node-app:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - mysql

  api:
    build: 
      dockerfile: Dockerfile
      context: ./server
    image: react-task/server
    volumes:
      - ./server:/app
      - node-api:/app/node_modules
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST_IP: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql:rw
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'countries'

volumes:
  todo-mysql-data:
  node-api:
  node-app:
    