services:
  app:
    build: 
      dockerfile: Dockerfile
      context: ./client
    image: react-task/client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    depends_on:
      - api
      - mysql

  api:
    build: 
      dockerfile: Dockerfile
      context: ./server
    image: react-task/server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'countries'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  todo-mysql-data:
    