services:
  app:
    build: 
      dockerfile: Dockerfile
      context: ./client
    image: task/client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - mysql

  api:
    build: 
      dockerfile: Dockerfile
      context: ./server
    image: task/server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      MYSQL_HOST: mysql 
      MYSQL_USER: Minh  
      MYSQL_PASSWORD: Tuongminh2001@
      MYSQL_HOST_IP: mysql
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: 'Tuongminh2001@'
      MYSQL_DATABASE: 'my_database'
      MYSQL_USER: 'Minh'
      MYSQL_PASSWORD: 'Tuongminh2001@'

volumes:
  mysql-data: